### ISSUE TITLE
Specify "alt" attribute for images

### ISSUE THREAD

**Issue by milantenk** [browniebroke/gatsby-image-gallery#492]
Thank you for this awesome library! 
Is there a way to specify `alt` HTML attributes for the images, that are displayed by the gallery?

**Comment by browniebroke** [comment]
Welcome! I didn't know other people were using it 😄 

It's not supported at the moment, but would be nice to add this capability. I assume you mean the `alt` attribute of the thumbnails? They could be given as a new nested prop of the `images` prop:

https://github.com/browniebroke/gatsby-image-gallery/blob/afb0ce6a43f9d465a070051d7cf68e36bf7a3ca7/gatsby-image-gallery/src/index.js#L96-L100

Something slighly related that was on my radar was the ability to pass extra options to the [underlying `Lightbox` component](https://github.com/frontend-collective/react-image-lightbox). I've created #493 for this.

**Comment by milantenk** [comment]
Yes, I meant the thumbnails. 😄 

Having a nested prop in the `images` would be great. Yes, exactly, adding the passed properties to
https://github.com/browniebroke/gatsby-image-gallery/blob/afb0ce6a43f9d465a070051d7cf68e36bf7a3ca7/gatsby-image-gallery/src/index.js#L67
would be perfect.

I would send a PR with these changes if it is okay for you. 😃

**Comment by browniebroke** [comment]
Sure, go ahead!
