### ISSUE TITLE
Add styles

### ISSUE THREAD

**Issue by mateBe95** [browniebroke/gatsby-image-gallery#540]
Hi, how to add own styles per image border for example... ;)?

**Comment by browniebroke** [comment]
Depends what you want to do, I guess:

- The `Img` component from `gatsby-image` has a customisable class name, if you want to style that directly:

  https://github.com/browniebroke/gatsby-image-gallery/blob/f41d50bc401c9cdacee8ca547804224696db1268/gatsby-image-gallery/src/index.js#L71

- If you to style the wrapper around each image, this is not supported at the moment, the wrapper component is almost fixed, you can only customise the margin:

  https://github.com/browniebroke/gatsby-image-gallery/blob/f41d50bc401c9cdacee8ca547804224696db1268/gatsby-image-gallery/src/index.js#L68

  https://github.com/browniebroke/gatsby-image-gallery/blob/f41d50bc401c9cdacee8ca547804224696db1268/gatsby-image-gallery/src/img-wrapper.js#L3-L5

To enable the second option, we could add an option to the `Gallery` component to either pass any component to use as wrapper or some extra CSS that we could inject in the current component.

## Option 1:

Passing down a custom component. Example: 

```
const ImgWrapper = styled.div`
  margin: 1rem;
  border-color: black;
  border-radius: 5px;
`

<Gallery images={images} imgWrapper={ImgWrapper}>
```

## Option 2

Passing down custom CSS. Example:

```
<Gallery images={images} imgWrapperStyles={{
	margin: '1rem',
	borderColor: 'black',
	borderRadius: '5px',
}}>
```

**Comment by mateBe95** [comment]
Seems implementation a to work well

**Comment by jakubziemba** [comment]
> Depends what you want to do, I guess:
> 
> * The `Img` component from `gatsby-image` has a customisable class name, if you want to style that directly:
>   https://github.com/browniebroke/gatsby-image-gallery/blob/f41d50bc401c9cdacee8ca547804224696db1268/gatsby-image-gallery/src/index.js#L71
> * If you to style the wrapper around each image, this is not supported at the moment, the wrapper component is almost fixed, you can only customise the margin:
>   https://github.com/browniebroke/gatsby-image-gallery/blob/f41d50bc401c9cdacee8ca547804224696db1268/gatsby-image-gallery/src/index.js#L68
>   
>   https://github.com/browniebroke/gatsby-image-gallery/blob/f41d50bc401c9cdacee8ca547804224696db1268/gatsby-image-gallery/src/img-wrapper.js#L3-L5
> 
> # Possible solution
> To enable the second option, we could add an option to the `Gallery` component to either pass any component to use as wrapper (a) or some extra CSS that we could inject in the current component (b).
> 
> ## Implementation a:
> Passing down a custom component. Example:
> 
> ```
> const ImgWrapper = styled.div`
>   margin: 1rem;
>   border-color: black;
>   border-radius: 5px;
> `
> 
> <Gallery images={images} imgWrapper={ImgWrapper}>
> ```
> 
> ## Implementation b
> Passing down custom CSS. Example:
> 
> ```
> <Gallery images={images} imgWrapperStyles={{
> 	margin: '1rem',
> 	borderColor: 'black',
> 	borderRadius: '5px',
> }}>
> ```

Hi, 
it would be great if we could somehow style the wrapper as well. I would like to change the max-width and flex-basis, cause on mobile it looks quite small. Any plans for making it possible soon?
