### ISSUE TITLE
Remove deprecated props

### ISSUE THREAD

**Issue by browniebroke** [browniebroke/gatsby-image-gallery#542]
Remove  the deprecated props `thumbs` and `fullImages`:

https://github.com/browniebroke/gatsby-image-gallery/blob/ead3b1f28bc1cbe0ecb5caa10bb62df50c08372a/gatsby-image-gallery/src/index.js#L114-L115

https://github.com/browniebroke/gatsby-image-gallery/blob/ead3b1f28bc1cbe0ecb5caa10bb62df50c08372a/gatsby-image-gallery/src/index.js#L14-L15

The associated code using them:

https://github.com/browniebroke/gatsby-image-gallery/blob/ead3b1f28bc1cbe0ecb5caa10bb62df50c08372a/gatsby-image-gallery/src/index.js#L29-L45

And tests for them, for example:

https://github.com/browniebroke/gatsby-image-gallery/blob/ead3b1f28bc1cbe0ecb5caa10bb62df50c08372a/gatsby-image-gallery/src/index.test.js#L89-L103

This should enable to simplify this part:

https://github.com/browniebroke/gatsby-image-gallery/blob/ead3b1f28bc1cbe0ecb5caa10bb62df50c08372a/gatsby-image-gallery/src/index.js#L22-L27

This will be a breaking change.

**Comment by slavakr** [comment]
Can you assign the issue to me please @browniebroke . Currently working on it, fixing some failing tests :)
