### ISSUE TITLE
Need a way to pass a title, caption, etc to an individual photo

### ISSUE THREAD

**Issue by calbatr0ss** [browniebroke/gatsby-image-gallery#552]
There doesn't seem to be a way to pass in an image title or image caption _per image_ through the `lightboxOptions` prop, it's just a static value for all images in the gallery.

**Comment by browniebroke** [comment]
This is correct, the `lightboxOptions` is not suitable for `title` or `caption`, only for common options. 

The `title` and `caption` may be customised by passing them along with each image [as explained in the README](https://github.com/browniebroke/gatsby-image-gallery#details). There is [an example](https://github.com/browniebroke/gatsby-image-gallery/blob/7e1365e1368f22cd7de383404550a4fc4ef295bd/example/src/pages/index.js#L9-L15) in the demo as well.

**Comment by browniebroke** [comment]
For a more realistic example, [I'm using it](https://github.com/browniebroke/carriere-web/blob/93b892f8ac4924f37e64f5c2ae01bdd8ff322912/src/templates/gallery-page.js#L45-L46) on one of my website, where the data is sourced from DatoCMS.
