### ISSUE TITLE
Dependency on gatsby-image: migrate to gatsby-plugin-image

### ISSUE THREAD

**Issue by bryoz** [browniebroke/gatsby-image-gallery#657]
As mentioned, this plugin relies on `gatsby-image` plugin, which has been deprecated and replaced with `gatsby-plugin-image`.

**Comment by browniebroke** [comment]
Good one, that was on my radar, but feel free to contribute.

**Comment by bryoz** [comment]
Fighting fires after a bunch of updates, but will take a look if I get a chance! 👍
