### ISSUE TITLE
Add OnClose callback

### ISSUE THREAD

**Issue by clariceabreu** [browniebroke/gatsby-image-gallery#658]
I've checked the code and as far as I get there is no `onClose` prop with a callback for when the user closes the `<Lightbox>`, right?

Can I make a contribution to add it? It would help me in my use case.
Something like that:

```
const Gallery = ({
  images = null,
  colWidth = 100 / 3,
  mdColWidth = 100 / 4,
  gutter = '0.25rem',
  imgClass = '',
  lightboxOptions = {},
 onClose = () => {}
}) => {

const onCloseLightbox = () => {
  setIsOpen(false)
  onclose()
}

...

<Lightbox
    mainSrc={fullArray[index]}
    nextSrc={fullArray[nextIndex]}
    prevSrc={fullArray[prevIndex]}
    onCloseRequest={onCloseLightbox}
    onMovePrevRequest={() => setIndex(prevIndex)}
    onMoveNextRequest={() => setIndex(nextIndex)}
    imageTitle={images[index].title}
    imageCaption={images[index].caption}
    {...lightboxOptions}
  />
...
```

Do you have any contributing guidelines/rules?

**Comment by clariceabreu** [comment]
cc: @browniebroke

**Comment by browniebroke** [comment]
Hello, and welcome! Thanks for the suggestion. I didn't need it in my use cases, but that would be a welcome addition, yes.

We don't have any guidelines no, but generally speaking, try to document the change somewhere in the readme, and write a simple test for it. The test doesn't have to be very fancy, the existing ones are pretty basic, they mostly test that rendering works. 

If you want to do more realistic/manual testing, you can also utilise the example to call your new code, but that's not required to merge your contribution, it's more for your own convenience.

**Comment by clariceabreu** [comment]
@browniebroke Can you please review PR #659? 
Sorry about the number of force pushes, I was fixing lint and didn't want to leave a commit to that, so I rebased to squash them.
