### ISSUE TITLE
Build warning

### ISSUE THREAD

**Issue by wildpow** [browniebroke/gatsby-image-gallery#702]
### The terminal warning I'm getting
```bash
warn ./node_modules/@browniebroke/gatsby-image-gallery/dist/gatsby-image-gallery.esm.js
Attempted import error: 'react-image-lightbox/style.css' does not contain a default export (imported as 'LightboxCSS').
```

#### Not 100% sure you can use named imports on css files like this even though [Webpack css-loader](https://webpack.js.org/loaders/css-loader/) references this exact usage.
https://github.com/browniebroke/gatsby-image-gallery/blob/197b551b5cf4d369d34960fa8998f3b363a9ca20/gatsby-image-gallery/src/index.tsx#L9

Should be able to just import the CSS per docs recommendation.
`import 'react-image-lightbox/style.css';`  
#### and skip this.
https://github.com/browniebroke/gatsby-image-gallery/blob/197b551b5cf4d369d34960fa8998f3b363a9ca20/gatsby-image-gallery/src/index.tsx#L31-L33

Seems like the styles are working though hence just a warning and this package in my tests is functioning as intended

**Comment by browniebroke** [comment]
Yes I tried a few things but couldn't make it work without warning. I decided to go with what worked, but I guess it might break at some point. Would be nice to fix 👍
