### ISSUE TITLE
lightbox icons are missing in production / public site.

### ISSUE THREAD

**Issue by arun54321** [browniebroke/gatsby-image-gallery#728]
Icons like close, next , zoom are missing on build. It is missing even in https://gatsby-image-gallery.netlify.app/ 
They work fine in develop mode.

**Comment by browniebroke** [comment]
Thanks to this, definitely a bug that cropped up recently, it was working fine at some point before.

**Comment by browniebroke** [comment]
Issue seems to be introduced by Gatsby 3.7.x and it goes away if you downgrade to Gatsby 3.6.x

For more details: https://github.com/gatsbyjs/gatsby/issues/31878

**Comment by browniebroke** [comment]
Will be fixed in Gatsby 3.9.x. I've updated the example to use the next version.

**Comment by Tiefflieger** [comment]
I am having this issue. I am using tailwind.
`
{
  "name": "gatsby-starter-default",
  "private": true,
  "description": "A simple starter to get up and developing quickly with Gatsby and TailwindCSS",
  "version": "0.3.0",
  "author": "Kostas Vrouvas <hello@kosvrouvas.com>",
  "dependencies": {
    "@browniebroke/gatsby-image-gallery": "^7.0.3",
    "@fontsource/quicksand": "^4.5.3",
    "@headlessui/react": "^1.4.3",
    "@heroicons/react": "^1.0.5",
    "@mdx-js/mdx": "^1.6.22",
    "@mdx-js/react": "^1.6.22",
    "@tailwindcss/forms": "^0.4.0",
    "@tailwindcss/typography": "^0.5.0",
    "autoprefixer": "^10.3.4",
    "babel-plugin-styled-components": "^2.0.2",
    "gatsby": "^4.6.0",
    "gatsby-image": "^3.11.0",
    "gatsby-plugin-gdpr-cookies": "^2.0.8",
    "gatsby-plugin-google-analytics": "^4.5.0",
    "gatsby-plugin-image": "^2.5.2",
    "gatsby-plugin-manifest": "^4.5.2",
    "gatsby-plugin-mdx": "^3.5.2",
    "gatsby-plugin-offline": "^5.5.2",
    "gatsby-plugin-postcss": "^5.5.0",
    "gatsby-plugin-purgecss": "^6.1.0",
    "gatsby-plugin-react-helmet": "^5.5.0",
    "gatsby-plugin-sharp": "^4.5.2",
    "gatsby-plugin-styled-components": "^5.6.0",
    "gatsby-remark-images": "^6.5.2",
    "gatsby-remark-relative-images": "^2.0.2",
    "gatsby-source-filesystem": "^4.6.0",
    "gatsby-transformer-json": "^4.5.0",
    "gatsby-transformer-remark": "^5.5.2",
    "gatsby-transformer-sharp": "^4.6.0",
    "postcss": "^8.3.4",
    "prop-types": "^15.8.1",
    "react": "^17.0.2",
    "react-cookie-consent": "^7.2.1",
    "react-dom": "^17.0.2",
    "react-helmet": "^6.1.0",
    "react-icons": "^4.3.1",
    "react-image-lightbox": "^5.1.4",
    "styled-components": "^5.3.3",
    "uninstall": "^0.0.0",
    "webpack": "^5.59.0"
  },
  "devDependencies": {
    "@iconify-icons/heroicons-outline": "^1.1.4",
    "prettier": "^2.5.1",
    "tailwindcss": "^3.0.15"
  },
  "keywords": [
    "gatsby"
  ],
  "license": "MIT",
  "scripts": {
    "build": "gatsby build",
    "develop": "gatsby develop",
    "format": "prettier --write \"**/*.{js,jsx,json,md}\"",
    "start": "npm run develop",
    "serve": "gatsby serve",
    "clean": "gatsby clean",
    "test": "echo \"Write tests! -> https://gatsby.dev/unit-testing\" && exit 1"
  },
  "repository": {
    "type": "git",
    "url": "https://github.com/kosvrouvas/gatsby-tailwindcss-starter"
  },
  "bugs": {
    "url": "https://github.com/kosvrouvas/gatsby-tailwindcss-starter/issues"
  }
}

`
